spring.application.name=online-exam
#server.port=7070
server.port=${PORT:8080}

# ===============================
# PostgreSQL / Neon Configuration
# ===============================
# PostgreSQL / Neon
spring.datasource.url=jdbc:postgresql://ep-bold-recipe-api32r8r-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pA4dgDS0jMKL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# File Upload
# ===============================
file.upload-dir=uploads